import Head from "next/head";
import type { NextPage } from "next";
import Layout from "@/components/Layout";
import withAuth from "src/lib/withAuth";

const Dashboard: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dashboard here</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <p> test </p>
      </Layout>
    </div>
  );
};

export default withAuth(Dashboard);
